name: Deploy to dev Firebase Hosting
on:
  pull_request:
    branches:
      - dev
env:
  CI: false
jobs:
  build:
    name: Build and deploy react app to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ELK_RESORT_LANDINGPAGE }}'
          projectId: elk-resort-landingpage
          channelId: dev
          expires: 1d
